p = 4
print(paste("theta has length", inla.pc.cormat.p2dim(p)))
theta = inla.pc.cormat.rtheta(n=1, p=4, lambda = 1)
print("sample theta:")
print(theta)
print(paste("log.dens", inla.pc.cormat.dtheta(theta, log=TRUE)))
r = inla.pc.cormat.theta2r(theta)
print("r:")
print(r)
R = inla.pc.cormat.r2R(r)
print("A sample from the non-exchangable prior, R:")
print(R)
R = inla.pc.cormat.permute(R)
print("A sample from the exchangable prior, R:")
print(R)
