#!/usr/bin/env bash

for d in ~/p/inla/binaries/Version_*; do
    
    echo -e -n "$d "
    (
	for i in $(seq 1 10); do
	    $d/64bit/inla.mkl.run -t2 Model.ini | grep stage1 | awk '{print $4}'
	done
    ) | awk '{ s = s + $1; } END{print s/NR}'
    
done

    
